"""
Supervisor dashboard page - reads escalations DB and allows override.
Place under pages/ so Streamlit multi-page picks it up.
"""

import streamlit as st
import utils
import json

st.title("Supervisor Dashboard — HITL Review")

# Initialize DB
utils.init_db()

status_filter = st.radio("View", ["PENDING","RESOLVED"], index=0)
cases = utils.get_escalations(status=status_filter)
if not cases:
    st.info("No cases.")
else:
    for c in cases:
        st.markdown(f"### Case {c['id']}")
        st.write("Timestamp:", c["timestamp"])
        st.write("User query:", c["user_query"])
        st.write("Flag reason:", c["flag_reason"])
        st.write("AI draft response:", c["flagged_ai_response"])
        with st.expander("Conversation history"):
            st.code(c["conversation_history"])
        override = st.text_area(f"Supervisor response for {c['id']}", key=c['id'])
        if st.button(f"Resolve {c['id']}", key="resolve_"+c['id']):
            # store supervisor response and run level_4 evolution loop
            utils.resolve_escalation(c['id'], override)
            # fetch case as dict and add supervisor_response to it for evolution
            case_dict = c.copy()
            case_dict["supervisor_response"] = override
            new_rule = utils.level_4_evolution_loop(case_dict)
            st.success(f"Resolved. Autogenerated rule: {new_rule.get('id')} pattern: {new_rule.get('pattern')}")
            st.experimental_rerun()

